// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct LoginInfo {
  var uid: String
  var token: String
  var expiredTime: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LoginInfo? {
    let uid = pigeonVar_list[0] as! String
    let token = pigeonVar_list[1] as! String
    let expiredTime = pigeonVar_list[2] as! Int64

    return LoginInfo(
      uid: uid,
      token: token,
      expiredTime: expiredTime
    )
  }
  func toList() -> [Any?] {
    return [
      uid,
      token,
      expiredTime,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PreLoginInfo {
  var number: String
  var privacyName: String
  var privacyURL: String
  var operatorType: String
  var expiredTime: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreLoginInfo? {
    let number = pigeonVar_list[0] as! String
    let privacyName = pigeonVar_list[1] as! String
    let privacyURL = pigeonVar_list[2] as! String
    let operatorType = pigeonVar_list[3] as! String
    let expiredTime = pigeonVar_list[4] as! Int64

    return PreLoginInfo(
      number: number,
      privacyName: privacyName,
      privacyURL: privacyURL,
      operatorType: operatorType,
      expiredTime: expiredTime
    )
  }
  func toList() -> [Any?] {
    return [
      number,
      privacyName,
      privacyURL,
      operatorType,
      expiredTime,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return LoginInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return PreLoginInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LoginInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PreLoginInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GYSdkApi {
  func initSDK(appId: String) throws
  func preLogin(timeout: Int64, completion: @escaping (Result<PreLoginInfo, Error>) -> Void)
  func isPreLoginResultValid() throws -> Bool
  func login(timeout: Int64, completion: @escaping (Result<LoginInfo, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GYSdkApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `GYSdkApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GYSdkApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initSDKChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_umeng_share.GYSdkApi.initSDK\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initSDKChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appIdArg = args[0] as! String
        do {
          try api.initSDK(appId: appIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initSDKChannel.setMessageHandler(nil)
    }
    let preLoginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_umeng_share.GYSdkApi.preLogin\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      preLoginChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutArg = args[0] as! Int64
        api.preLogin(timeout: timeoutArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      preLoginChannel.setMessageHandler(nil)
    }
    let isPreLoginResultValidChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_umeng_share.GYSdkApi.isPreLoginResultValid\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPreLoginResultValidChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isPreLoginResultValid()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isPreLoginResultValidChannel.setMessageHandler(nil)
    }
    let loginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_umeng_share.GYSdkApi.login\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loginChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutArg = args[0] as! Int64
        api.login(timeout: timeoutArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loginChannel.setMessageHandler(nil)
    }
  }
}
