// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.haijunwei.flutter_gysdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginInfo (
  val uid: String,
  val token: String,
  val expiredTime: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginInfo {
      val uid = pigeonVar_list[0] as String
      val token = pigeonVar_list[1] as String
      val expiredTime = pigeonVar_list[2] as Long
      return LoginInfo(uid, token, expiredTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uid,
      token,
      expiredTime,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreLoginInfo (
  val number: String,
  val privacyName: String,
  val privacyURL: String,
  val operatorType: String,
  val expiredTime: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreLoginInfo {
      val number = pigeonVar_list[0] as String
      val privacyName = pigeonVar_list[1] as String
      val privacyURL = pigeonVar_list[2] as String
      val operatorType = pigeonVar_list[3] as String
      val expiredTime = pigeonVar_list[4] as Long
      return PreLoginInfo(number, privacyName, privacyURL, operatorType, expiredTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      number,
      privacyName,
      privacyURL,
      operatorType,
      expiredTime,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreLoginInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LoginInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PreLoginInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GYSdkApi {
  fun initSDK(appId: String)
  fun preLogin(timeout: Long, callback: (Result<PreLoginInfo>) -> Unit)
  fun isPreLoginResultValid(): Boolean
  fun login(timeout: Long, callback: (Result<LoginInfo>) -> Unit)

  companion object {
    /** The codec used by GYSdkApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `GYSdkApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GYSdkApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_umeng_share.GYSdkApi.initSDK$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.initSDK(appIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_umeng_share.GYSdkApi.preLogin$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutArg = args[0] as Long
            api.preLogin(timeoutArg) { result: Result<PreLoginInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_umeng_share.GYSdkApi.isPreLoginResultValid$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isPreLoginResultValid())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_umeng_share.GYSdkApi.login$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutArg = args[0] as Long
            api.login(timeoutArg) { result: Result<LoginInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
