// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVdK6hLAToYWjrus9nNnyy9Qsjk0q-9U', // 使用 json 中的 current_key
    appId:
        '1:1040993520143:android:75ee1a2fce1feebe69b17a', // 使用 json 中的 mobilesdk_app_id
    messagingSenderId: '1040993520143', // 使用 json 中的 project_number
    projectId: 'pawfect-abroad', // 使用 json 中的 project_id
    storageBucket:
        'pawfect-abroad.firebasestorage.app', // 使用 json 中的 storage_bucket
    // 如果您还需要使用其他服务（如数据库），可能需要添加以下参数：
    // databaseURL: 'https://pawfect-abroad.firebaseio.com', // 请根据您的数据库实际URL填写
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-I-aXUxHfLODYesZiy85iyLlbBArCN2E', // 使用 json 中的 current_key
    appId:
        '1:902252899234:ios:9ff3d22f3b6d80325620fb', // 使用 json 中的 mobilesdk_app_id
    messagingSenderId: '902252899234', // 使用 json 中的 project_number
    projectId: 'pawfex-ai--ios', // 使用 json 中的 project_id
    storageBucket:
        'pawfex-ai--ios.firebasestorage.app', // 使用 json 中的 storage_bucket
    // 如果您还需要使用其他服务（如数据库），可能需要添加以下参数：
    // databaseURL: 'https://pawfect-abroad.firebaseio.com', // 请根据您的数据库实际URL填写
  );
}
